
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "nirmal",
  "email": "nirmalfageria1522@gmail.com",
  "address": "vpo katrathal",
  "dateOfBirth": "2005-02-13",
  "registeredDate": "2026-07-13"
}

###