spring.application.name=patient-service
#
#spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/patient_service}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=${POSTGRES_USER:postgres}
#spring.datasource.password=${POSTGRES_PASSWORD:postgres}
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

server.port=4000

logging.level.root=info
